### ISSUE TITLE
Improve IO locality in MultiplePathsFromGCRootsComputerImpl bfs

### ISSUE THREAD

**Issue by eclipsewebmaster** [eclipse-mat/mat#46]
| --- | --- |
| Bugzilla Link | [582821](https://bugs.eclipse.org/bugs/show_bug.cgi?id=582821) |
| Status | ASSIGNED |
| Importance | P3 normal |
| Reported | Dec 31, 2023 15:01 EDT |
| Modified | Jan 17, 2024 08:54 EDT |
| Version | 1.15 |

**Comment by eclipsewebmaster** [comment]
By Jason Koch on Dec 31, 2023 15:03

https://git.eclipse.org/r/c/mat/org.eclipse.mat/+/205956

**Comment by eclipsewebmaster** [comment]
By Andrew Johnson on Jan 03, 2024 14:44

I think this is okay.\
Another case of slow I/O is a HPROF file compressed with gzip (not so much with chucked GZIP as generated by the JVM, or by export HPROF with the chunked option). This can involve restarting the gunzip from a PosStream position, and depending on memory this might be more widely spaced than the 1MB chunked multi-memory gzip file.

**Comment by eclipsewebmaster** [comment]
By Jason Koch on Jan 16, 2024 17:35

Note that this changes the results presented in the tests because the sort() order changes the traversal order at each BFS layer. Removing the sort during each iteration confirms this.

**Comment by eclipsewebmaster** [comment]
By Jason Koch on Jan 16, 2024 17:35

the *regression test suite, that is

**Comment by jasonk000** [comment]
this was merged in [https://git.eclipse.org/r/c/mat/org.eclipse.mat/+/205956 , [this commit](https://github.com/eclipse-mat/mat/commit/6d27b35d936a62c546a96ea465e61930f8fcaf36).

This is as much as stands out to me for now.

**Comment by jasonk000** [comment]
This is ready to close @krumts but I don't have perms =)

**Comment by krumts** [comment]
> but I don't have perms =)
@jasonk000 , this shouldn't be the case. I was able to close it, and I guess/hope every committer on the project should be able too. Not sure if this is something special for the migrated issues. Will try to figure it out

**Comment by krumts** [comment]
@jasonk000 I see you are shown as "Contributor" while I am show as "Member" of the eclipse-mat organization. There was an invite after the move. Did you get one? I don't find you under members of the org.

**Comment by jasonk000** [comment]
I had a look, and I do not see an invite. Checked my spam/deleted as well and did not see it.

**Comment by kgibm** [comment]
I believe it requires setting your GitHub user ID in the Eclipse developer configuration. Did you do that?

![image](https://github.com/eclipse-mat/mat/assets/6618433/b2de7873-ae10-4129-83da-74cacb9e80e6)

This is the invite email I got:

![image](https://github.com/eclipse-mat/mat/assets/6618433/5fc89793-c918-47b3-8f23-5d9d34cb3f84)

**Comment by krumts** [comment]
@jasonk000 the web masters confirmed that the link to your github id is missing. Once you link it, you will automatically get the invitation to join (within 2h).

**Comment by jasonk000** [comment]
Got it! Thanks for the pointers.
