### ISSUE TITLE
Nightly build files not publishing?

### ISSUE THREAD

**Issue by jasonk000** [eclipse-mat/mat#64]
I notice the nightly build doesn't seem to be updating on the MAT update website?

https://download.eclipse.org/mat/snapshots/update-site/

Last publish date looks to be June 6.

  | .. |   |   |  
-- | -- | -- | -- | --
  | binary | 11.4K | 2024-06-06 11:28 |  
  | features | 72K | 2024-06-06 11:28 |  
  | plugins | 15.1M | 2024-06-06 11:28 |  
  | artifacts.jar | 5.6k | 2024-06-06 11:28 |  
  | artifacts.xml.xz | 4.8k | 2024-06-06 11:28 |  
  | content.jar | 24.5k | 2024-06-06 11:27 |  
  | content.xml.xz | 10.9k | 2024-06-06 11:28 |  
  | p2.index | 172 | 2024-06-06 11:28

Do we need to finalise the work in #55 GH Actions workflow? I had assumed the old pipelines would continue to run post-migration.

**Comment by jasonk000** [comment]
@krumts it looks like this is dash/cyclone issue,

I can see you made this commit -- 4535fc2, but I do not see exactly where we specify the license. I assume since we do not provide one that it resorts to the dash-license-plugin source, which looks to be 


```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "this.approvedLicenses" is null
```

I can see the history here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=582480

**Comment by krumts** [comment]
#66 fixed the build and I confirmed that also the contents of the update site got updated.

**Comment by jasonk000** [comment]
Ah, great work, I'd never checked for redirects, and must have mixed up my report. Thank you for taking care of it.

**Comment by krumts** [comment]
It turned out, that the latest version of the license-tool-plugin works fine with the redirects. I just didn't see that this version exists (although I checked :) ). So, I made a second change - upgrading to the latest version and removed the explicit URL config.
