### ISSUE TITLE
Prepare MAT 1.16.0 Release

### ISSUE THREAD

**Issue by krumts** [eclipse-mat/mat#81]
Let's use this issue to track the activities needed to do the next Memory Analyzer release - version 1.16.0.

I created a release record: https://projects.eclipse.org/projects/tools.mat/releases/1.16.0 and requested a release review with the goal to release on  20 Dec 2024.

Some of the things we need to complete:
- build the standalone MAT with the platform components released with Eclipse 2024-12
- prepare new & noteworthy
- update the website, once the release is ready

**Comment by jasonk000** [comment]
@kgibm, the changes are two-fold:

Indexing and IO improvements

- A number of changes to parsing/indexing stage performance primarily through improved parallelism.

- Improvements to support more parallel read IO especially relevant to slower devices (eg: when indexes are stored on an NFS volume).

**Comment by krumts** [comment]
A short update:
- I think I added all the missing pieces to prepare the release. I copied the artefacts from the last snapshot build to there permanent release download location and would like to stick to these unless we face some real blockers
- we got an approval for the release on the tools-pmc mailing list
- the EMO has created an issue in their backlog for the release review: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/853 . Looking at the progress there, I think we'd be able to keep the target release date 20 December
- Once we finalize the release, I will add the 1.16.0 version to the first milestone of Eclipse 2025-03, so that we have an up-to-date MAT in the next Eclipse SimRel
- I will prepare the updates to the website (a short news message, updated downloads page) and have them ready for 20 Dec

**Comment by krumts** [comment]
The 1.16.0 release is now out. I've updated the website and sent a short announcement on the mailing list.
